### ISSUE TITLE
Facebook API :: Login 

### ISSUE THREAD

**Issue by emotionify-hacktoberfest-2015** [emotionify-hacktoberfest-2015/facebook-api#1]
Facebook Login using an simple HTML file and a JavaScript file. 

Needed to connect to Facebook to access the User Profile Data (Profile Information, Albums, Photos, etc). 

Later on: Expose this Facebook Login Method through a service/library/api.

**Comment by Margretor** [comment]
You can assign this task to me. I will start working in a few hours.

**Comment by emotionify-hacktoberfest-2015** [comment]
Assigned. Will review the pull request in a few seconds.

**Comment by Margretor** [comment]
I have the basic script up and running.
