### ISSUE TITLE
Facebook API :: getPerson/getProfileData

### ISSUE THREAD

**Issue by emotionify-hacktoberfest-2015** [emotionify-hacktoberfest-2015/facebook-api#2]
Write a method for Facebook Profile data retrieval. 

Later on: Add method to library/service/api.

**Comment by Margretor** [comment]
I have uploaded a .js that should take care of this issue.

**Comment by emotionify-hacktoberfest-2015** [comment]
Have you retested it, to close this issue?

**Comment by Margretor** [comment]
It does the job.

**Comment by emotionify-hacktoberfest-2015** [comment]
Haha, nice one. Closing Issue.
