### ISSUE TITLE
Facebook API :: getProfilePhoto

### ISSUE THREAD

**Issue by emotionify-hacktoberfest-2015** [emotionify-hacktoberfest-2015/facebook-api#3]
Expose a method for Profile Photo retrieval. 
@return: bitmap (or link to profile photo, depending on the chosen architecture).

**Comment by Margretor** [comment]
I will start working on this issue in a few hours, you can assign to me.

**Comment by Margretor** [comment]
codra277 can work on this issue while I am focusing on the Facebook API :: getPerson/getProfileData.

**Comment by emotionify-hacktoberfest-2015** [comment]
Please keep the Facebook API files prefixed with fb_filename.js, such as: fb_init.js, fb_login.js, fb_getInfo.js, fb_getProfilePic.js, etc.

**Comment by emotionify-hacktoberfest-2015** [comment]
Create new Pull Request to fix the issue. Will create another issue.
